### PR TITLE
Update userparameters-gluster.conf

### PR DESCRIPTION
**Pull request by TNAJanssen**

### CODE REVIEW

**Comment by burner1024** [comment]
what's the meaning of this?

**Comment by tenajsystems** [comment]
@TNAJanssen, when I use the userparameters-gluster.conf, I am getting this error in Zabbix: ```sh: 1: set: Illegal option -o pipefail``` anyway to fix this? When I run one of the commands on the cli i get the right value but in zabbix i get the output error as I stated before.

**Comment by burner1024** [comment]
you have bash? which version?

**Comment by tenajsystems** [comment]
@burner1024, Yes I do, I have bash ```version 4.3.48``` on Ubuntu 16.04

**Comment by burner1024** [comment]
That strange. You can omit it then, although that will make the contruction slightly less robust.

**Comment by TNAJanssen** [comment]
Sorry for the late reaction, yeah i did the same because of ubuntu 16.04 and 18.04 issues regarding the -o pipefail

**Comment by burner1024** [comment]
OK... it seems that Zabbix is using /bin/sh, which is linked to /bin/dash, which doesn't support pipefail option.
I'm not sure if the best way to handle this is to disable it, rather than changing Zabbix shell to bash.

**Comment by TNAJanssen** [comment]
Hmm, i will try that when i have the change!

**Comment by tenajsystems** [comment]
Having the command in a bash script with this ```#!/bin/bash``` defined worked.

**Comment by tenajsystems** [comment]
Noticed that, for the Number of offline bricks user-parameter, it only triggers when the node itself goes down. When the brick goes down(with a N) without the node itself going down, zabbix doesn't trigger any alert for it. Not sure how to cause a brick to go down though but I had an incidence when a brick went down without me knowing about it because zabbix didn't alert me.

**Comment by burner1024** [comment]
@tenajsystems that should trigger offline peers though, no?
As for userparameters, it'd probably be cleaner to move most of the work to a script, yes. Like with heal.sh. I can't test now, but I'd accept such a pull.

**Comment by tenajsystems** [comment]
@burner1024 No it doesn't trigger it. It only does when the node itself goes down. I have created a pull request #5 which has the commands in a script and more items to monitor. The items in the template would have to  be created though

**Comment by burner1024** [comment]
need to create and enumerate the items/triggers, then

**Pull request merged**
