### PR TITLE
update heal.sh to be more universal over glusfs

### PR DESCRIPTION
**Pull request by blka**

### CODE REVIEW

**Review by burner1024 — COMMENTED** [review]
I don't have access too Gluster handy... can you show sample output where this change is useful?

**Comment by blka** [comment]
gluster package 3.7.6  on Ubuntu 16.04.2 LTS has output of the split-brain like below:

sudo gluster volume heal my_vol info split-brain | grep -A1 "Brick my-host:/var/lib/docker/glusterfs" Brick my-host:/var/lib/docker/glusterfs
Number of entries in split-brain: 0

you got 
| grep 'Number of entries: ' - which is wrong in this version with colon ":"

and when you try  
echo "Number of entries in split-brain: 0" | awk '{print $4}'  this will be "in" as output, 
so when we take the last char from line instead of $4 from awk will be much easier

of course this could be wrong if you have more than >9 brick in gluster cluster.

**Review by burner1024 — CHANGES_REQUESTED** [review]
Oh I see, they changed the format.
How about awk '{print $NF}', to grab any number of bricks?

**Review by burner1024 — APPROVED** [review]
great, thank you!

**Pull request merged**
