### PR TITLE
Fix for newer Gluster versions

### PR DESCRIPTION
**Pull request by TNAJanssen**

### CODE REVIEW

**Comment by burner1024** [comment]
For which version is it? Backwards compatible?

**Comment by TNAJanssen** [comment]
I tested it with the GlusterFS 4.0, maybe somebody can test it with an older version?

**Comment by burner1024** [comment]
I don't have an environment to test at the moment, so if anyones wants to chime in that would be helpful.
It seems that 4.0 is short term maintenance. If by the time 4.1 LTM comes out there's no further info, I'll just accept it.

**Comment by istoph** [comment]
I can confirm the fix on glusterfs 3.8.8 on debian stretch 9
It also fix #2

**Comment by burner1024** [comment]
Done.

**Pull request merged**
